language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qYcAWL6b/Jy1kkaGaJoW1+sjZY3hum+cdvJIwZQ3srhQGGT+90CUI+Zi8tRQp80IGR38gRe8VSpl+CAHQa/aInzVcbvqj6aPXbedHoUe/WD2mbYAWNbM1Zki3ZMc5VqzN4FOZshVI7agnT/rWq6I57jGEEqtSWCnje49Aos5OUsnIUsucqfmTYzIe63nN1QGcBW2derrbQw5JIhl5fwlfczfpap/uvgH6+YNTt6CWtG8Jy9PdPkHq2UXB3CWIQKJfiV9Zi04FANfVWGcNBh/xesZlHUbAMhklzz8IECHw/aBHQEFgCvAQmLEJaTmEeOhUWlNmvBVZyRBWVKdkHH2cajsEi3FghTX+UlBbwIZ4f5AAy2TzXPzt9X2POEIGbu/xBHxG+ozZsOQU9nacEijhcIn6H79VZJOWQ6bq3vd1idLIMxWsiB/VDhzGwqhSFID77DXmjeNXp+/pgAx7LsxyaApmP4B2s+FPSWdxLNWpSs9xs3MAe6ErY2lWCdguB++v1vkNKwtYRNGrJFzPqkkzbXGgjMp2bpcWkUoifO2gEVTdzUCQbXD9IGXJp1/UFlWUm7aH/goxiCzJk0BgJsQsZQPD8ifPtGzgICFcl9QM3ra08/yupu7E5GGRdEiQOCM2lmI97PgOhxuLhqc/l190xHTCFBC64EQArxaeW2G1m8=
  file:
    - 'nlcst-search.js'
    - 'nlcst-search.min.js'
  on:
    tags: true
